<a href="https://colab.research.google.com/github/Vladimir2303850/MyAnalyticsProjects/blob/main/%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%20%D1%81%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Импортируйте NumPy as np

In [ ]:
import numpy as np

#### 2. Создайте массив из 10 нулей

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Создайте массив из 10 единиц

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Создайте массив из 10 пятёрок

In [ ]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Создайте массив целых чисел от 10 до 50 включительно

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Создайте массив всех чётных чисел от 10 до 50 включительно

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Создайте матрицу 3x3 со значениями от 0 до 8 включительно

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Создайте единичную матрицу размером 3x3

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. С помощью NumPy сгенерируйте случайное число в диапазоне от 0 до 1<br><br>&emsp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [ ]:
np.random.rand(1)

array([0.9922416])

#### 10. С помощью NumPy сгенерируйте массив из 25 случайных чисел, выбранных из стандартного нормального распределения<br><br>&emsp;&ensp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [ ]:
np.random.randn(25)

array([-0.58748065,  1.05295725, -1.69513316,  1.97086885,  0.42242126,
       -1.46142951, -0.10497173,  1.31352437, -0.93631687,  0.30511832,
       -1.028522  ,  0.55612997,  0.48212349, -1.50834091, -0.66819   ,
        0.67868996, -2.16084586, -0.82936967, -0.97042765,  0.82673985,
        1.81467201, -1.36907108,  1.39618182, -0.17193818,  0.93291286])

#### 11. Создайте указанную ниже матрицу:

In [ ]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Создайте массив из 20 равноудалённых друг от друга точек между 0 и 1:

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Индексация Numpy

Здесь Вы будете работать с некоторой матрицей - чтобы создать её, запустите следующую ячейку! После этого мы попросим Вас воспроизвести несколько результатов работы с этой матрицей:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу (подсказка - используйте индексацию).

In [ ]:

mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [ ]:
mat[3,4]

np.int64(20)

#### 15. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [ ]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

#### 16. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [ ]:

mat[4,:]

array([21, 22, 23, 24, 25])

#### 17. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [ ]:

mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Операции в NumPy

#### 18. Найдите сумму всех чисел в матрице mat

In [ ]:
mat.sum()

np.int64(325)

#### 19. Найдите среднеквадратичное отклонение значений в матрице mat

In [ ]:

mat.std()

np.float64(7.211102550927978)

#### 20. Найдите сумму каждой из колонок в матрице mat

In [ ]:

mat.sum(axis=0)

array([55, 60, 65, 70, 75])